# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "tty-prompt", "~> 0.22.0"

gem "date", "~> 3.0"

gem "terminal-table", "~> 1.8"

gem "colorize", "~> 0.8.1"
